# -*- coding: utf-8 -*-
"""LVADSUSR157_ Lab 2_ Classification___Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G8TIjLWhDaJxqMHhkGYfb-ti7zPDlTIX
"""

import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

df = pd.read_csv("/content/penguins_classification.csv")
df

df.info()

df.isnull().sum()

df.isna().sum()

#dropping null values
df.dropna(axis= 0, inplace=True)
df.isnull().sum()

df.duplicated().sum()

df.species = pd.to_numeric(df.species,errors='coerce')
df.info()

df.island = pd.to_numeric(df.island,errors='coerce')
df.info()

num_df = df.select_dtypes(include=np.number)
df2=df.iloc[:, :]

print(df2)

df.species.value_counts()

df2['species'].replace(to_replace = 'Adelie', value=1, inplace=True)
df2['species'].replace(to_replace = 'Gentoo' , value=0, inplace= True)

df_dummies=pd.get_dummies(df2)
print(df_dummies.head())

df2.select_dtypes(include=np.number).corr()['species']
df_co=df_dummies.corr()['species']
df_co.plot(kind = 'bar')

# Data cleaning of churn data part

df_species = df_dummies['species']
df_species
df_species.dropna(axis =0, inplace=True)
df_dummies.dropna(axis =0, inplace=True)
df_dummies2=df_dummies.copy()

#Normalize data
y=df.species
enc = LabelEncoder()
y_enc = enc.fit_transform(y)
y_enc = y_enc.reshape(-1,1)

# Converting entire data between the range of 0 to 1
from sklearn.preprocessing import MinMaxScaler
features = df_dummies2.columns.values
scaler = MinMaxScaler(feature_range = (0,1))
scaler.fit(df_dummies2)
X=pd.DataFrame(scaler.transform(df_dummies2))
X.columns = features
X

#dropping null values
num_df.dropna(axis= 0, inplace=True)
num_df

X_train, X_test, y_train, y_test = train_test_split(num_df,df_species,train_size=0.8,random_state=20)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

## fitting logistic regression
model = LogisticRegression()
# model = linear_model.LogisticRegression(random_state=16)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)


cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))











